server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:batchdemodb;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&autoReconnect=true
    hikari:
      password: root
      username: root
    jpa:
      open-in-view: true
      show-sql: true
      hibernate:
        ddl-auto: update
      #database: mysql
      database: H2

    # 禁止项目启动时运行job
  batch:
    job:
      enabled: false
